version: '1'
services:
  master_postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'